CONTIKI_PROJECT = eeprom_write_contiki_test
all: $(CONTIKI_PROJECT)

CONTIKI = /home/gsmetal/workspace/os

CONTIKI_BACKYARD_TREE = on
CONTIKI_LOCAL_TREE = on

AVRDUDE_OPTIONS = -v
AVRDUDE_PORT = /dev/ttyUSB0
AVRDUDE_PROGRAMMER = duemilanove

include $(CONTIKI)/Makefile.include
