#!/usr/bin/env ruby

require File.expand_path('../config.rb', __FILE__)

if ARGV.size < 1
    STDERR.print <<EOF
    Usage: #{$0} input_binary_file
EOF
    exit(1)
end

fbin = ARGV[0]
fhex = File.join($config[:hex_dir], "#{File.split(fbin)[1]}.hex")

`avr-objcopy -O ihex #{fbin} -R .eeprom #{fhex} -v`
puts fhex

