CONTIKI_TARGET_DIRS = . dev
CONTIKI_CORE = contiki-avr-our-main
CONTIKI_TARGET_MAIN = ${CONTIKI_CORE}.o

CONTIKI_TARGET_SOURCEFILES += ${CONTIKI_CORE}.c cfs-eeprom.c device.c led.c can.c can-drv.c

include $(CONTIKI_LOCAL_MODULES)/led_module/Makefile.led_module

CONTIKI_SOURCEFILES += $(CONTIKI_TARGET_SOURCEFILES) 

MCU=at90can128

CONTIKI_PLAT_DEFS = -DF_CPU=16000000UL

CONTIKI_CPU=$(CONTIKI)/cpu/avr
include $(CONTIKI_CPU)/Makefile.avr
