CONTIKI_PROJECT = can_broadcast2_contiki_app
all: $(CONTIKI_PROJECT)

CONTIKI = ../../trunk/

CONTIKI_BACKYARD_TREE = on
CONTIKI_LOCAL_TREE = on

AVRDUDE_OPTIONS = -v
AVRDUDE_PORT = /dev/ttyUSB1
AVRDUDE_PROGRAMMER = jtag1

OPTI = 0

include $(CONTIKI)/Makefile.include
