network:
    server_ip: 127.0.0.1
    server_port: 8563
    port: 8566

log_synchronization:
    period: 0.16
    tries: 3

extensions:
    - turnstile
    # etc.

database:
    filename: test.db
    debug: False

can_net:
    recieve_delay: 0.01
    interface: can0
    confirmation_timeout: 5
    confirmation_period: 0.01
