#Configuration of server
server:
    #Period between synchronizations, in minutes
    sync_period: 0.16
    tries: 1
    sending_delay: 0.5
    nodes_port: 8566
    port: 8563
    
#Configuration of server database
database:
    host: localhost
    
    user: root
 
    #Should we encrypt the password and how?
    password: ''
    
    db: MAN
    debug: False
