LIBS += config.c net_device.c pmd_system.c interrupt.c ftimer.c can_net_core.c can_net_middle.c can_net.c can_protocols.c
CONTIKIDIRS += ${addprefix $(CONTIKI_LOCAL)/core/,lib dev net .}
CONTIKIDIRS += $(CONTIKI_LOCAL)

CONTIKI_LOCAL_DRIVERS = $(CONTIKI_LOCAL)/drivers

include $(CONTIKI_LOCAL_DRIVERS)/net_led/Makefile.led
include $(CONTIKI_LOCAL_DRIVERS)/net_button/Makefile.button
