#ifndef PMD_NET_SYSTEM_H_
#define PMD_NET_SYSTEM_H_

#define PMD_NET_SYSTEM_CONFIG_REQUEST       1
#define PMD_NET_SYSTEM_CONFIG_FULL          2
#define PMD_NET_SYSTEM_CONFIG_SECTION_ADD   3
#define PMD_NET_SYSTEM_CONFIG_SECTION_DEL   4

#endif /* PMD_NET_SYSTEM_H_ */
