# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2



_MAN_MESSAGE_FULLMANDB_TABLETYPE_NODE = descriptor.Descriptor(
  name='TableType_node',
  full_name='man_message.FullMANDB.TableType_node',
  filename='man_db_msg.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='man_message.FullMANDB.TableType_node.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ip', full_name='man_message.FullMANDB.TableType_node.ip', index=1,
      number=2, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_MAN_MESSAGE_FULLMANDB_TABLETYPE_CONTROLLER = descriptor.Descriptor(
  name='TableType_controller',
  full_name='man_message.FullMANDB.TableType_controller',
  filename='man_db_msg.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='man_message.FullMANDB.TableType_controller.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='address', full_name='man_message.FullMANDB.TableType_controller.address', index=1,
      number=2, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='node_id', full_name='man_message.FullMANDB.TableType_controller.node_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_MAN_MESSAGE_FULLMANDB_TABLETYPE_POINT = descriptor.Descriptor(
  name='TableType_point',
  full_name='man_message.FullMANDB.TableType_point',
  filename='man_db_msg.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='man_message.FullMANDB.TableType_point.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='type', full_name='man_message.FullMANDB.TableType_point.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='controller_id', full_name='man_message.FullMANDB.TableType_point.controller_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='reader', full_name='man_message.FullMANDB.TableType_point.reader', index=3,
      number=4, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_MAN_MESSAGE_FULLMANDB_TABLETYPE_USER_GROUP = descriptor.Descriptor(
  name='TableType_user_group',
  full_name='man_message.FullMANDB.TableType_user_group',
  filename='man_db_msg.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='man_message.FullMANDB.TableType_user_group.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name', full_name='man_message.FullMANDB.TableType_user_group.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_MAN_MESSAGE_FULLMANDB_TABLETYPE_USER = descriptor.Descriptor(
  name='TableType_user',
  full_name='man_message.FullMANDB.TableType_user',
  filename='man_db_msg.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='man_message.FullMANDB.TableType_user.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name', full_name='man_message.FullMANDB.TableType_user.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='surname', full_name='man_message.FullMANDB.TableType_user.surname', index=2,
      number=3, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='patronymic', full_name='man_message.FullMANDB.TableType_user.patronymic', index=3,
      number=4, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='gender', full_name='man_message.FullMANDB.TableType_user.gender', index=4,
      number=5, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_MAN_MESSAGE_FULLMANDB_TABLETYPE_EM_MARINE_CARD = descriptor.Descriptor(
  name='TableType_em_marine_card',
  full_name='man_message.FullMANDB.TableType_em_marine_card',
  filename='man_db_msg.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='man_message.FullMANDB.TableType_em_marine_card.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='code', full_name='man_message.FullMANDB.TableType_em_marine_card.code', index=1,
      number=2, type=3, cpp_type=2, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='user_id', full_name='man_message.FullMANDB.TableType_em_marine_card.user_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_MAN_MESSAGE_FULLMANDB_TABLETYPE_POINT_GROUP = descriptor.Descriptor(
  name='TableType_point_group',
  full_name='man_message.FullMANDB.TableType_point_group',
  filename='man_db_msg.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='man_message.FullMANDB.TableType_point_group.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name', full_name='man_message.FullMANDB.TableType_point_group.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_MAN_MESSAGE_FULLMANDB_TABLETYPE_SCRIPT = descriptor.Descriptor(
  name='TableType_script',
  full_name='man_message.FullMANDB.TableType_script',
  filename='man_db_msg.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='man_message.FullMANDB.TableType_script.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='condition_code', full_name='man_message.FullMANDB.TableType_script.condition_code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_MAN_MESSAGE_FULLMANDB_TABLETYPE_ACCESS = descriptor.Descriptor(
  name='TableType_access',
  full_name='man_message.FullMANDB.TableType_access',
  filename='man_db_msg.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='man_message.FullMANDB.TableType_access.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='script_id', full_name='man_message.FullMANDB.TableType_access.script_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='point_group_id', full_name='man_message.FullMANDB.TableType_access.point_group_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='user_group_id', full_name='man_message.FullMANDB.TableType_access.user_group_id', index=3,
      number=4, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_MAN_MESSAGE_FULLMANDB_TABLETYPE_POINT_GROUP_LINK = descriptor.Descriptor(
  name='TableType_point_group_link',
  full_name='man_message.FullMANDB.TableType_point_group_link',
  filename='man_db_msg.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='man_message.FullMANDB.TableType_point_group_link.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='point_id', full_name='man_message.FullMANDB.TableType_point_group_link.point_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='point_group_id', full_name='man_message.FullMANDB.TableType_point_group_link.point_group_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_MAN_MESSAGE_FULLMANDB_TABLETYPE_USER_GROUP_LINK = descriptor.Descriptor(
  name='TableType_user_group_link',
  full_name='man_message.FullMANDB.TableType_user_group_link',
  filename='man_db_msg.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='man_message.FullMANDB.TableType_user_group_link.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='user_id', full_name='man_message.FullMANDB.TableType_user_group_link.user_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='user_group_id', full_name='man_message.FullMANDB.TableType_user_group_link.user_group_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_MAN_MESSAGE_FULLMANDB_TABLETYPE_LOG = descriptor.Descriptor(
  name='TableType_log',
  full_name='man_message.FullMANDB.TableType_log',
  filename='man_db_msg.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='man_message.FullMANDB.TableType_log.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='time', full_name='man_message.FullMANDB.TableType_log.time', index=1,
      number=2, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='decision', full_name='man_message.FullMANDB.TableType_log.decision', index=2,
      number=3, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='point_id', full_name='man_message.FullMANDB.TableType_log.point_id', index=3,
      number=4, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='code', full_name='man_message.FullMANDB.TableType_log.code', index=4,
      number=5, type=3, cpp_type=2, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='code_type', full_name='man_message.FullMANDB.TableType_log.code_type', index=5,
      number=6, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_MAN_MESSAGE_FULLMANDB_TABLETYPE_DATABASE_SEND_LOG = descriptor.Descriptor(
  name='TableType_database_send_log',
  full_name='man_message.FullMANDB.TableType_database_send_log',
  filename='man_db_msg.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='man_message.FullMANDB.TableType_database_send_log.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='begin_time', full_name='man_message.FullMANDB.TableType_database_send_log.begin_time', index=1,
      number=2, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='end_time', full_name='man_message.FullMANDB.TableType_database_send_log.end_time', index=2,
      number=3, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='node_id', full_name='man_message.FullMANDB.TableType_database_send_log.node_id', index=3,
      number=4, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_MAN_MESSAGE_FULLMANDB = descriptor.Descriptor(
  name='FullMANDB',
  full_name='man_message.FullMANDB',
  filename='man_db_msg.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='node', full_name='man_message.FullMANDB.node', index=0,
      number=1, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='controller', full_name='man_message.FullMANDB.controller', index=1,
      number=2, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='point', full_name='man_message.FullMANDB.point', index=2,
      number=3, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='user_group', full_name='man_message.FullMANDB.user_group', index=3,
      number=4, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='user', full_name='man_message.FullMANDB.user', index=4,
      number=5, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='em_marine_card', full_name='man_message.FullMANDB.em_marine_card', index=5,
      number=6, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='point_group', full_name='man_message.FullMANDB.point_group', index=6,
      number=7, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='script', full_name='man_message.FullMANDB.script', index=7,
      number=8, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='access', full_name='man_message.FullMANDB.access', index=8,
      number=9, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='point_group_link', full_name='man_message.FullMANDB.point_group_link', index=9,
      number=10, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='user_group_link', full_name='man_message.FullMANDB.user_group_link', index=10,
      number=11, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='log', full_name='man_message.FullMANDB.log', index=11,
      number=12, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='database_send_log', full_name='man_message.FullMANDB.database_send_log', index=12,
      number=13, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_MAN_MESSAGE = descriptor.Descriptor(
  name='man_message',
  full_name='man_message',
  filename='man_db_msg.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='message_type', full_name='man_message.message_type', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='db', full_name='man_message.db', index=1,
      number=2, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_MAN_MESSAGE_FULLMANDB.fields_by_name['node'].message_type = _MAN_MESSAGE_FULLMANDB_TABLETYPE_NODE
_MAN_MESSAGE_FULLMANDB.fields_by_name['controller'].message_type = _MAN_MESSAGE_FULLMANDB_TABLETYPE_CONTROLLER
_MAN_MESSAGE_FULLMANDB.fields_by_name['point'].message_type = _MAN_MESSAGE_FULLMANDB_TABLETYPE_POINT
_MAN_MESSAGE_FULLMANDB.fields_by_name['user_group'].message_type = _MAN_MESSAGE_FULLMANDB_TABLETYPE_USER_GROUP
_MAN_MESSAGE_FULLMANDB.fields_by_name['user'].message_type = _MAN_MESSAGE_FULLMANDB_TABLETYPE_USER
_MAN_MESSAGE_FULLMANDB.fields_by_name['em_marine_card'].message_type = _MAN_MESSAGE_FULLMANDB_TABLETYPE_EM_MARINE_CARD
_MAN_MESSAGE_FULLMANDB.fields_by_name['point_group'].message_type = _MAN_MESSAGE_FULLMANDB_TABLETYPE_POINT_GROUP
_MAN_MESSAGE_FULLMANDB.fields_by_name['script'].message_type = _MAN_MESSAGE_FULLMANDB_TABLETYPE_SCRIPT
_MAN_MESSAGE_FULLMANDB.fields_by_name['access'].message_type = _MAN_MESSAGE_FULLMANDB_TABLETYPE_ACCESS
_MAN_MESSAGE_FULLMANDB.fields_by_name['point_group_link'].message_type = _MAN_MESSAGE_FULLMANDB_TABLETYPE_POINT_GROUP_LINK
_MAN_MESSAGE_FULLMANDB.fields_by_name['user_group_link'].message_type = _MAN_MESSAGE_FULLMANDB_TABLETYPE_USER_GROUP_LINK
_MAN_MESSAGE_FULLMANDB.fields_by_name['log'].message_type = _MAN_MESSAGE_FULLMANDB_TABLETYPE_LOG
_MAN_MESSAGE_FULLMANDB.fields_by_name['database_send_log'].message_type = _MAN_MESSAGE_FULLMANDB_TABLETYPE_DATABASE_SEND_LOG
_MAN_MESSAGE.fields_by_name['db'].message_type = _MAN_MESSAGE_FULLMANDB

class man_message(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class FullMANDB(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    
    class TableType_node(message.Message):
      __metaclass__ = reflection.GeneratedProtocolMessageType
      DESCRIPTOR = _MAN_MESSAGE_FULLMANDB_TABLETYPE_NODE
    
    class TableType_controller(message.Message):
      __metaclass__ = reflection.GeneratedProtocolMessageType
      DESCRIPTOR = _MAN_MESSAGE_FULLMANDB_TABLETYPE_CONTROLLER
    
    class TableType_point(message.Message):
      __metaclass__ = reflection.GeneratedProtocolMessageType
      DESCRIPTOR = _MAN_MESSAGE_FULLMANDB_TABLETYPE_POINT
    
    class TableType_user_group(message.Message):
      __metaclass__ = reflection.GeneratedProtocolMessageType
      DESCRIPTOR = _MAN_MESSAGE_FULLMANDB_TABLETYPE_USER_GROUP
    
    class TableType_user(message.Message):
      __metaclass__ = reflection.GeneratedProtocolMessageType
      DESCRIPTOR = _MAN_MESSAGE_FULLMANDB_TABLETYPE_USER
    
    class TableType_em_marine_card(message.Message):
      __metaclass__ = reflection.GeneratedProtocolMessageType
      DESCRIPTOR = _MAN_MESSAGE_FULLMANDB_TABLETYPE_EM_MARINE_CARD
    
    class TableType_point_group(message.Message):
      __metaclass__ = reflection.GeneratedProtocolMessageType
      DESCRIPTOR = _MAN_MESSAGE_FULLMANDB_TABLETYPE_POINT_GROUP
    
    class TableType_script(message.Message):
      __metaclass__ = reflection.GeneratedProtocolMessageType
      DESCRIPTOR = _MAN_MESSAGE_FULLMANDB_TABLETYPE_SCRIPT
    
    class TableType_access(message.Message):
      __metaclass__ = reflection.GeneratedProtocolMessageType
      DESCRIPTOR = _MAN_MESSAGE_FULLMANDB_TABLETYPE_ACCESS
    
    class TableType_point_group_link(message.Message):
      __metaclass__ = reflection.GeneratedProtocolMessageType
      DESCRIPTOR = _MAN_MESSAGE_FULLMANDB_TABLETYPE_POINT_GROUP_LINK
    
    class TableType_user_group_link(message.Message):
      __metaclass__ = reflection.GeneratedProtocolMessageType
      DESCRIPTOR = _MAN_MESSAGE_FULLMANDB_TABLETYPE_USER_GROUP_LINK
    
    class TableType_log(message.Message):
      __metaclass__ = reflection.GeneratedProtocolMessageType
      DESCRIPTOR = _MAN_MESSAGE_FULLMANDB_TABLETYPE_LOG
    
    class TableType_database_send_log(message.Message):
      __metaclass__ = reflection.GeneratedProtocolMessageType
      DESCRIPTOR = _MAN_MESSAGE_FULLMANDB_TABLETYPE_DATABASE_SEND_LOG
    DESCRIPTOR = _MAN_MESSAGE_FULLMANDB
  DESCRIPTOR = _MAN_MESSAGE

